# Pytorch_basic

In [1]:
# numpy로 텐서 만들기
import numpy as np

# 1D with Numpy
t = np.array([0.,1.,2.,3.,4.,5.,6.])

print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [2]:
print('Rank of t: ',t.ndim) # 차원
print('Shape of t: ',t.shape) # 크기

# (7,)은 (1,7)을 의미함 -> 1x7의 크기를 가지는 벡터

Rank of t:  1
Shape of t:  (7,)


In [3]:
import torch
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2)) # mul도 곱셈을 수행하는 메소드

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Tensor manipulation

### view(),squeeze(), unsqueeze()는 텐서의 원소 수를 그대로 유지하면서 모양과 차원을 조절함

In [4]:
# view -> 원소의 수를 유지하면서 텐서의 크기 변경

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [5]:
# 3차원 텐서에서 2차원 텐서로 변경

# view([-1,3]) -> -1의 의미는 첫번째 차원의 경우는 파이토치에게 만ㅌ기는 것이고, 두번째 차원
# 의 길이는 3을 가지도록한다. (2,2,3) -> (2x2,3) -> (4,3)

# view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야한다.
# 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유지한다.
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [6]:
# 3차원 텐서에서 3차원 텐서로 차원은 유지하되 크기만 바꾸기

# (2x2x3) -> (4x1x3)

print(ft.view([-1,1,3])) # -1을 사용함으로써 ?x1x3의 형태, ?은 당연히 4가 되어 4x1x3 형태됨
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [7]:
# Squeeze - 차원이 1인 경우에 해당 차원 제거

ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [8]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [9]:
# Unsqueeze - 특정 위치에 1인 차원 추가
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [10]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미함
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [11]:
# 텐서 연결
# 두 텐서를 연결해서 입력으로 사용하는 것은 두 가지 정보를 모두 사용한다는 뜻
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

print(torch.cat([x,y],dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [12]:
# dim을 0으로 하면 (2x2) 텐서가 (4x2)가 된다.
# dim을 1로 하면 (2x2) 텐서가 두 개 함쳐져서 (2x4)가 된다.
print(torch.cat([x,y],dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [13]:
# 스택킹 -> 벡터를 순차적으로 쌓기
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [14]:
# ones_like -> 동일한 크기지만 1로만 채워진 텐서 생성
# zeros_like -> 동일한 크기지만 0으로만 채워진 텐서 생성
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [15]:
# 덮어쓰기 연산 -> _ 사용

x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) 

print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) 

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
