# Linear Regression

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 random seed
torch.manual_seed(1)

In [2]:
x_train  = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [3]:
print(x_train.shape)
print(y_train.shape)

torch.Size([3, 1])
torch.Size([3, 1])


In [4]:
# 가중치 0으로 초기화
# 학습을 통해 값이 변경되는 변수임을 명시 -> requires_grad=True
W = torch.zeros(1,requires_grad=True)

print(W)

tensor([0.], requires_grad=True)


In [5]:
# b도 초기화
b = torch.zeros(1,requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [6]:
# 선형회귀 공식 가설 세우기 f = wx +b
hypothesis = x_train*W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [7]:
# cost function
cost = torch.mean((hypothesis-y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [8]:
# Gradient descent 구현
optimizer = optim.SGD([W,b],lr=0.02)

In [9]:
# gradient 0으로 초기화
optimizer.zero_grad()
# cost function 미분해서 graident 계산
cost.backward()
# W,b 업뎃
optimizer.step()

In [10]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)


# 원하는만큼 gd 반복
nb_epochs=2000

optimizer = optim.SGD([W,b],lr=0.02)

for epoch in range(nb_epochs):
  hypothesis = x_train*W+b

  cost = torch.mean((hypothesis-y_train)**2)

  # gradient 0으로 초기화
  optimizer.zero_grad()
  # cost function 미분해서 graident 계산
  cost.backward()
  # W,b 업뎃
  optimizer.step()

  if epoch%100 ==0:
    print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 0.373, b: 0.160 Cost: 18.666666
Epoch  100/2000 W: 1.801, b: 0.453 Cost: 0.029732
Epoch  200/2000 W: 1.877, b: 0.280 Cost: 0.011340
Epoch  300/2000 W: 1.924, b: 0.173 Cost: 0.004325
Epoch  400/2000 W: 1.953, b: 0.107 Cost: 0.001650
Epoch  500/2000 W: 1.971, b: 0.066 Cost: 0.000629
Epoch  600/2000 W: 1.982, b: 0.041 Cost: 0.000240
Epoch  700/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch  800/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch  900/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1000/2000 W: 1.997, b: 0.006 Cost: 0.000005
Epoch 1100/2000 W: 1.998, b: 0.004 Cost: 0.000002
Epoch 1200/2000 W: 1.999, b: 0.002 Cost: 0.000001
Epoch 1300/2000 W: 1.999, b: 0.001 Cost: 0.000000
Epoch 1400/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1500/2000 W: 2.000, b: 0.001 Cost: 0.000000
Epoch 1600/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1700/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1800/2000 W: 2.000, b: 0.000 Cost: 0.000000
Epoch 1900/2000 W: 2.000, b: 0.000 Cost: 0.000000

## 1. 파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징이 있기 때문에, optimizer.zero_grad()를 통해 미분값을 0으로 계속 초기화 시켜줘야한다.

## 2. torch.manual_seed()를 사용하면 다른 컴퓨터에서 실행시켜도 동일한 결과를 얻을 수 있는데, 그 이유는 torch.manual_seed()는 난수발생 순서와 값을 동일하게 보장해주기 때문이다.

## 3. 텐서에는 requires_grad라는 속성이 있다. 이것을 True로 설정하면 자동 미분 기능이 적용되고, 어떤 복잡한 구조던 파라미터들에 모두 이 기능이 적용된다. 이렇게 연산하면 계산 그래프가 생성되고 backward 함수를 호출하면 그래프로부터 자동으로 미분이 계산된다.

## 자동 미분 기능 -> Autograd

In [11]:
w = torch.tensor(2.0,requires_grad=True)

In [12]:
y = w**2
z = 2*y+5

z.backward() #  backward로 해당 수식의 w에 대한 기울기 계산

In [13]:
print("Derivative of W:{}".format(w.grad))

Derivative of W:8.0


## 다중 선형 회귀 (Multivariable Linear Regression)

In [14]:

# 독립변수 3개와 종속변수 1개
# H(x) = w1x1 + w2x2 + w3x3 +b

x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 가중치도 3개 선언!
w1 = torch.zeros(1,requires_grad=True)
w2 = torch.zeros(1,requires_grad=True)
w3 = torch.zeros(1,requires_grad=True)

b = torch.zeros(1,requires_grad=True)

In [15]:
optimizer = optim.SGD([w1,w2,w3,b],lr = 1e-5)

nb =epochs= 1000

for epoch in range(nb_epochs+1):
  hypothesis = x1_train*w1 + x2_train*w2 + x3_train*w3 + b # matmul로 가능

  cost = torch.mean((hypothesis-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/2000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/2000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/2000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/2000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/2000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/2000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/2000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/2000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/2000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/2000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/2000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390
Epoch 1100/2000 w1: 0.722 w2: 0.608 w3: 0.680 b: 0.009 Cost: 1.038574
Epoch 1200/2000 w1: 0.727 w2: 0.603 w3: 0.681 b: 0.010 Cost: 0.999884
Epoch 1300/2000 w1: 0.731 w2: 0.599 w3: 0.681 b: 0.010 Cost: 0.963217
Epoch 1400/2000 

In [16]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  # 5x3 형태 
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 가중치도 3개 선언!
# w1 = torch.zeros(1,requires_grad=True)
# w2 = torch.zeros(1,requires_grad=True)
# w3 = torch.zeros(1,requires_grad=True)
W = torch.zeros((3,1),requires_grad=True) # 3x1 형태

b = torch.zeros(1,requires_grad=True)

optimizer = optim.SGD([W,b],lr = 1e-5)

nb =epochs= 20

for epoch in range(nb_epochs+1):
  # hypothesis = x1_train*w1 + x2_train*w2 + x3_train*w3 + b # matmul로 가능
  hypothesis = x_train.matmul(W) + b

  cost = torch.mean((hypothesis-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
        print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
            epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
        ))

Epoch    0/2000 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch  100/2000 hypothesis: tensor([154.0433, 185.0925, 175.8312, 198.5701, 141.2221]) Cost: 5.754573
Epoch  200/2000 hypothesis: tensor([154.0278, 185.0649, 175.9335, 198.5128, 141.2284]) Cost: 5.512386
Epoch  300/2000 hypothesis: tensor([154.0120, 185.0385, 176.0329, 198.4569, 141.2353]) Cost: 5.281667
Epoch  400/2000 hypothesis: tensor([153.9960, 185.0133, 176.1295, 198.4022, 141.2426]) Cost: 5.061907
Epoch  500/2000 hypothesis: tensor([153.9797, 184.9892, 176.2233, 198.3488, 141.2504]) Cost: 4.852424
Epoch  600/2000 hypothesis: tensor([153.9632, 184.9662, 176.3143, 198.2966, 141.2586]) Cost: 4.652731
Epoch  700/2000 hypothesis: tensor([153.9465, 184.9442, 176.4029, 198.2456, 141.2672]) Cost: 4.462265
Epoch  800/2000 hypothesis: tensor([153.9296, 184.9232, 176.4888, 198.1958, 141.2762]) Cost: 4.280604
Epoch  900/2000 hypothesis: tensor([153.9126, 184.9032, 176.5724, 198.1471, 141.2855]) Cost: 4.107261
Epoch 

# nn.Module로 구현

In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as f

torch.manual_seed(1)

In [18]:
# y=2x 를 가정된 상태에서 만들어진 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

# 단순 선형 회귀이므로 input_dim=1, output_dim = 1
model = nn.Linear(1,1)

print(list(model.parameters())) # 모델의 W,b를 출력

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [19]:
# optimizer 설정
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [21]:
nb_epochs = 2000

for epoch in range(nb_epochs+1):
  prediction = model(x_train)

  cost = F.mse_loss(prediction,y_train) # pytorch에 내장되어있는 mse

  # cost로 prediction 개선
  # gradient를 0으로 초기화
  optimizer.zero_grad()
  # cost함수 미분으로 gradient 게산
  cost.backward() # backward 연산 -> 학습과정에서 cost function을 미분하여 기울기 구하는것
  # W,b 업뎃
  optimizer.step()

  if epoch%100==0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [22]:
# x에 임의의 값 넣어서 예측값 도출
new_var = torch.FloatTensor([4.0])

pred_y = model(new_var) # forward 연산
print("Prediction of model when input = 4: {}".format(pred_y))

Prediction of model when input = 4: tensor([7.9989], grad_fn=<AddBackward0>)


In [23]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


## Multivaritive linear regression by using nn

In [24]:
import torch
import torch.nn as nn
import torch.nn.functional as f

torch.manual_seed(1)

In [26]:
# H(x) = w1x1 + w2x2 + w3x3 + b
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 독립변수가 3개이므로, input_dim = 3, output_dim은 종속변수가 1개이므로 1
model = nn.Linear(3,1)

In [27]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [28]:
optimizer = torch.optim.SGD(model.parameters(),lr = 1e-5)

nb_epochs = 2000

for epoch in range(nb_epochs+1):
  prediction = model(x_train)

  cost = F.mse_loss(prediction,y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [29]:
# 입력값 [73,80,75]에 대한 예측값 도출

new_var = torch.FloatTensor([[73,80,75]])
pred_y = model(new_var)
print("prediction of model when input is [73,80,75]:{}".format(pred_y))

prediction of model when input is [73,80,75]:tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [30]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


# Using class

In [31]:
# torch.nn.Module을 상속받는 파이썬 클래스
class LinearRegressionModel(nn.Module):
  def __init__(self): # 생성자 정의
    super().__init__() # super()를 통해 여기서 만든 클래스는 nn.Module 클래스의
    # 속성들을 가지고 초기화됨
    self.linear = nn.Linear(1,1) 

  def forward(self,x):
    return self.linear(x)

model = LinearRegressionModel()

# forward 함수는 model 객체를 데이터와 함께 호출하면 자동으로 수행이 된다.

In [33]:
class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)

  def forward(self,x):
    return self.linear(x)
model = MultivariateLinearRegressionModel()

In [34]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [35]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [36]:
class LinearRegressionModel(nn.Module):
  def __init__(self): # 생성자 정의
    super().__init__() # super()를 통해 여기서 만든 클래스는 nn.Module 클래스의
    # 속성들을 가지고 초기화됨
    self.linear = nn.Linear(1,1) 

  def forward(self,x):
    return self.linear(x)

model = LinearRegressionModel()

In [37]:
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)

In [38]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)

  cost = F.mse_loss(prediction,y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [39]:
# 다중선형회귀
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [40]:
class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3,1)

  def forward(self,x):
    return self.linear(x)
model = MultivariateLinearRegressionModel()

In [41]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs=2000

for epoch in range(nb_epochs+1):
  prediction = model(x_train)

  cost = F.mse_loss(prediction,y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 42134.707031
Epoch  100/2000 Cost: 5.960053
Epoch  200/2000 Cost: 5.654707
Epoch  300/2000 Cost: 5.365413
Epoch  400/2000 Cost: 5.091429
Epoch  500/2000 Cost: 4.831834
Epoch  600/2000 Cost: 4.585997
Epoch  700/2000 Cost: 4.353045
Epoch  800/2000 Cost: 4.132426
Epoch  900/2000 Cost: 3.923438
Epoch 1000/2000 Cost: 3.725488
Epoch 1100/2000 Cost: 3.537972
Epoch 1200/2000 Cost: 3.360339
Epoch 1300/2000 Cost: 3.192076
Epoch 1400/2000 Cost: 3.032686
Epoch 1500/2000 Cost: 2.881703
Epoch 1600/2000 Cost: 2.738666
Epoch 1700/2000 Cost: 2.603199
Epoch 1800/2000 Cost: 2.474860
Epoch 1900/2000 Cost: 2.353289
Epoch 2000/2000 Cost: 2.238115


# Mini Batch and Data Load

## Graident Descent를 사용했었지만, 데이터의 수가 엄청 많다면 전체 데이터에 대해 graident descent를 사용하는 것은 느린데다가 많은 계산량으로 메모리 초과가 발생할 수도 있다.
## 따라서 전체 데이터를 더 작은 단위로 나누어서 해당 단위로 학습하는 개념이 나오게 되었는데, 이를 Mini Batch라 한다.

## 전체 데이터를 미니 배치 단위로 나누게 되면, 미니 배치만큼만 가져가서 gradient descent를 수행하고 마지막 미니 배치까지 이를 반복한다. 전체 데이터에 대한 학습이 1회 끝나면, 1 epoch가 끝나는 형식이다.
### epoch -> 전체 training data가 학습에 한번 사용된 주기

## 미니 배치 학습에서는 미니 배치의 개수만큼 경사 하강법을 수행해야 전체 데이터가 한번 전부 사용되어 1 epoch가 됨. 미니 배치의 크기는 batch size라 한다.

## batch size는 보통 2의 제곱수를 사용하는데, 그 이유는 CPU와 GPU의 메모리가 2의 배수이므로 배치 크기가 2의 제곱수일때 데이터 송수신의 효율을 높일 수 있기 때문이다.

## iteration은 한번의 epoch 내에서 이루어지는 매개변수인 W,b의 업데이트 횟수이다. 전체 데이터가 2000개고, batch size를 200으로 한다면 iteration의 수는 10개다. 이는 한번의 epoch 당 매개변수 업데이트가 10번 이루어짐을 의미한다.

In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

dataset = TensorDataset(x_train,y_train)
# shuffle=True를 하게 되면 Epoch마다 데이터셋을 섞어서 데이터가 학습되는 순서를 바꾼다.
# 모델이 데이터셋의 순서에 익숙해지지 않도록 순서를 섞게되면, 학습의 효율을
# 보다 높일 수 있으므로 True를 주는 것을 권장 
dataloader = DataLoader(dataset,batch_size=2, shuffle=True)

In [44]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs=20

for epoch in range(nb_epochs+1):
  for batch_idx, samples in enumerate(dataloader):
    x_train,y_train = samples

    prediction = model(x_train)

    cost = F.mse_loss(prediction,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 54524.218750
Epoch    0/20 Batch 2/3 Cost: 8945.384766
Epoch    0/20 Batch 3/3 Cost: 2403.548828
Epoch    1/20 Batch 1/3 Cost: 1564.037354
Epoch    1/20 Batch 2/3 Cost: 550.310242
Epoch    1/20 Batch 3/3 Cost: 128.874252
Epoch    2/20 Batch 1/3 Cost: 35.747013
Epoch    2/20 Batch 2/3 Cost: 24.368774
Epoch    2/20 Batch 3/3 Cost: 13.028359
Epoch    3/20 Batch 1/3 Cost: 0.577810
Epoch    3/20 Batch 2/3 Cost: 5.028281
Epoch    3/20 Batch 3/3 Cost: 1.949444
Epoch    4/20 Batch 1/3 Cost: 2.790044
Epoch    4/20 Batch 2/3 Cost: 4.539840
Epoch    4/20 Batch 3/3 Cost: 1.471585
Epoch    5/20 Batch 1/3 Cost: 0.735286
Epoch    5/20 Batch 2/3 Cost: 2.351912
Epoch    5/20 Batch 3/3 Cost: 7.989922
Epoch    6/20 Batch 1/3 Cost: 2.292079
Epoch    6/20 Batch 2/3 Cost: 3.429396
Epoch    6/20 Batch 3/3 Cost: 0.660007
Epoch    7/20 Batch 1/3 Cost: 1.045065
Epoch    7/20 Batch 2/3 Cost: 4.478187
Epoch    7/20 Batch 3/3 Cost: 0.089189
Epoch    8/20 Batch 1/3 Cost: 0.152515
Epoch

In [45]:
new_var = torch.FloatTensor([[73,80,75]])
pred_y = model(new_var)
print(pred_y)

tensor([[152.1972]], grad_fn=<AddmmBackward0>)


## Custom Dataset
### torch.utils.data.Dataset을 상속받아 직접 custom dataset을 만드는 경우도 있다.

In [46]:
import torch
import torch.nn.functional as f

from torch.utils.data import Dataset
from torch.utils.data import DataLoader

class CustomDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]
  
  # 총 데이터 개수 리턴
  def __len__(self):
    return len(self.x_data)
  
  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 pytorch의 tensor 형태로 리턴
  def __getitem__(self,idx):
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x,y

dataset = CustomDataset()
dataloader = DataLoader(dataset,batch_size=2, shuffle=True)

model = torch.nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(),lr=1e-5)

nb_epochs=20

for epoch in range(nb_epochs+1):
  for batch_idx, samples in enumerate(dataloader):
    x_train, y_train= samples

    prediction = model(x_train)

    cost = F.mse_loss(prediction,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 60260.054688
Epoch    0/20 Batch 2/3 Cost: 24187.050781
Epoch    0/20 Batch 3/3 Cost: 7451.262207
Epoch    1/20 Batch 1/3 Cost: 2172.791016
Epoch    1/20 Batch 2/3 Cost: 426.008667
Epoch    1/20 Batch 3/3 Cost: 176.225464
Epoch    2/20 Batch 1/3 Cost: 51.904434
Epoch    2/20 Batch 2/3 Cost: 25.064507
Epoch    2/20 Batch 3/3 Cost: 25.065657
Epoch    3/20 Batch 1/3 Cost: 4.560037
Epoch    3/20 Batch 2/3 Cost: 3.363674
Epoch    3/20 Batch 3/3 Cost: 13.814692
Epoch    4/20 Batch 1/3 Cost: 5.317976
Epoch    4/20 Batch 2/3 Cost: 3.416877
Epoch    4/20 Batch 3/3 Cost: 7.356547
Epoch    5/20 Batch 1/3 Cost: 4.508004
Epoch    5/20 Batch 2/3 Cost: 3.371403
Epoch    5/20 Batch 3/3 Cost: 13.739931
Epoch    6/20 Batch 1/3 Cost: 4.974255
Epoch    6/20 Batch 2/3 Cost: 10.525476
Epoch    6/20 Batch 3/3 Cost: 1.861449
Epoch    7/20 Batch 1/3 Cost: 4.675714
Epoch    7/20 Batch 2/3 Cost: 7.297645
Epoch    7/20 Batch 3/3 Cost: 2.033331
Epoch    8/20 Batch 1/3 Cost: 5.895012
E